name: Validate the repositories.py file as valid python

on:
  pull_request:
    paths:
      - repositories.py

jobs:
  validate-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Merge PR into target branch
      run: git merge origin/${{ github.event.pull_request.base.ref }}
  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Validate Python file
      run: python -m py_compile repositories.py